// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/internal/goexperiment/exp_heapminimum512kib_on.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/internal/goexperiment/exp_heapminimum512kib_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.heapminimum512kib
// +build goexperiment.heapminimum512kib

package goexperiment

const HeapMinimum512KiB = true
const HeapMinimum512KiBInt = 1
