// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/internal/goexperiment/exp_regabiargs_on.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/internal/goexperiment/exp_regabiargs_on.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build goexperiment.regabiargs
// +build goexperiment.regabiargs

package goexperiment

const RegabiArgs = true
const RegabiArgsInt = 1
