// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/internal/goexperiment/exp_regabireflect_off.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/internal/goexperiment/exp_regabireflect_off.go:1
// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.regabireflect
// +build !goexperiment.regabireflect

package goexperiment

const RegabiReflect = false
const RegabiReflectInt = 0
