// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/internal/bio/buf_nommap.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/internal/bio/buf_nommap.go:1
// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !darwin && !dragonfly && !freebsd && !linux && !netbsd && !openbsd
// +build !darwin,!dragonfly,!freebsd,!linux,!netbsd,!openbsd

package bio

func (r *Reader) sliceOS(length uint64) ([]byte, bool) {
	return nil, false
}
