// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/sort/slice_go113.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/sort/slice_go113.go:1
// Copyright 2017 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.13
// +build go1.13

package sort

import "internal/reflectlite"

var reflectValueOf = reflectlite.ValueOf
var reflectSwapper = reflectlite.Swapper
