// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/noder/func.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/noder/func.go:1
// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package noder

import (
	"bootstrap/cmd/compile/internal/base"
	"bootstrap/cmd/compile/internal/ir"
	"bootstrap/cmd/compile/internal/syntax"
	"bootstrap/cmd/compile/internal/typecheck"
	"bootstrap/cmd/compile/internal/types"
	"bootstrap/cmd/internal/src"
)

func (g *irgen) funcBody(fn *ir.Func, recv *syntax.Field, sig *syntax.FuncType, block *syntax.BlockStmt) {
	typecheck.Func(fn)

	// TODO(mdempsky): Remove uses of ir.CurFunc and
	// typecheck.DeclContext after we stop relying on typecheck
	// for desugaring.
	outerfn, outerctxt := ir.CurFunc, typecheck.DeclContext
	ir.CurFunc = fn

	typ := fn.Type()
	if param := typ.Recv(); param != nil {
		g.defParam(param, recv, ir.PPARAM)
	}
	for i, param := range typ.Params().FieldSlice() {
		g.defParam(param, sig.ParamList[i], ir.PPARAM)
	}
	for i, result := range typ.Results().FieldSlice() {
		g.defParam(result, sig.ResultList[i], ir.PPARAMOUT)
	}

	// We may have type-checked a call to this function already and
	// calculated its size, including parameter offsets. Now that we've
	// created the parameter Names, force a recalculation to ensure
	// their offsets are correct.
	types.RecalcSize(typ)

	if block != nil {
		typecheck.DeclContext = ir.PAUTO

		fn.Body = g.stmts(block.List)
		if fn.Body == nil {
			fn.Body = []ir.Node{ir.NewBlockStmt(src.NoXPos, nil)}
		}
		fn.Endlineno = g.makeXPos(block.Rbrace)

		if base.Flag.Dwarf {
			g.recordScopes(fn, sig)
		}
	}

	ir.CurFunc, typecheck.DeclContext = outerfn, outerctxt
}

func (g *irgen) defParam(param *types.Field, decl *syntax.Field, class ir.Class) {
	typecheck.DeclContext = class

	var name *ir.Name
	if decl.Name != nil {
		name, _ = g.def(decl.Name)
	} else if class == ir.PPARAMOUT {
		name = g.obj(g.info.Implicits[decl])
	}

	if name != nil {
		param.Nname = name
		param.Sym = name.Sym() // in case it was renamed
	}
}
