// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/test/test.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/test/test.go:1
package test
