// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/logopt/escape_bootstrap.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/logopt/escape_bootstrap.go:1
// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !go1.8
// +build !go1.8

package logopt

// For bootstrapping with an early version of Go
func pathEscape(s string) string {
	panic("This should never be called; the compiler is not fully bootstrapped if it is.")
}
