// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/gc/bootstrap.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/gc/bootstrap.go:1
// Copyright 2017 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !go1.8
// +build !go1.8

package gc

import (
	"bootstrap/cmd/compile/internal/base"
	"runtime"
)

func startMutexProfiling() {
	base.Fatalf("mutex profiling unavailable in version %v", runtime.Version())
}
