// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/gc/trace.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/compile/internal/gc/trace.go:1
// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.7
// +build go1.7

package gc

import (
	"os"
	tracepkg "runtime/trace"

	"bootstrap/cmd/compile/internal/base"
)

func init() {
	traceHandler = traceHandlerGo17
}

func traceHandlerGo17(traceprofile string) {
	f, err := os.Create(traceprofile)
	if err != nil {
		base.Fatalf("%v", err)
	}
	if err := tracepkg.Start(f); err != nil {
		base.Fatalf("%v", err)
	}
	base.AtExit(tracepkg.Stop)
}
