// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/internal/objabi/zbootstrap.go

//line /Users/litiantian/code/m_code/read_go_code/go_source/go/src/cmd/internal/objabi/zbootstrap.go:1
// Code generated by go tool dist; DO NOT EDIT.

package objabi

const stackGuardMultiplierDefault = 1
